export default {
    products: [{
        _id: '1',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        countInStock: 6,
    },
    {
        _id: '2',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/d1.jpg',
        price: 70,
        brand: 'Adidas',
        rating: 4.6,
        numReviews: 11,
        countInStock: 7,
    },
    {
        _id: '3',
        name: 'Best Shirt',
        category: 'Pants',
        image: '/images/d1.jpg',
        price: 80,
        brand: 'Levis',
        rating: 4.7,
        numReviews: 12,
        countInStock: 8,
    },
    {
        _id: '4',
        name: 'Best Shirt',
        category: 'Pants',
        image: '/images/d1.jpg',
        price: 80,
        brand: 'Levis',
        rating: 4.7,
        numReviews: 12,
        countInStock: 9,
    },
]
}